In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel('raw_data.xlsx')

In [4]:
df.head()

,Date,Coal_RB_4800_FOB_London_Close_USD,Coal_RB_5500_FOB_London_Close_USD,Coal_RB_5700_FOB_London_Close_USD,Coal_RB_6000_FOB_CurrentWeek_Avg_USD,Coal_India_5500_CFR_London_Close_USD,Price_WTI,Price_Brent_Oil,Price_Dubai_Brent_Oil,Price_ExxonMobil,Price_Shenhua,Price_All_Share,Price_Mining,Price_LNG_Japan_Korea_Marker_PLATTS,Price_ZAR_USD,Price_Natural_Gas,Price_ICE,Price_Dutch_TTF,Price_Indian_en_exg_rate
0,2020-04-02,41.00,53.22,64.7,97.56,60.50,25.32,29.94,26.16,40.40,14.58,45060.69,35562.37,2.860,0.05411,1.552,81.14,6.935,NaN
1,2020-04-03,40.34,52.36,63.1,70.57,62.03,28.34,34.11,29.39,39.21,14.14,44598.70,35258.30,2.845,0.05245,1.621,80.99,6.920,45.02
2,2020-04-06,40.34,52.36,63.1,70.57,62.03,26.08,33.05,27.45,40.47,14.26,46240.35,37032.31,2.850,0.05351,1.731,84.43,7.285,NaN
3,2020-04-07,40.34,52.36,63.1,70.57,62.03,23.63,31.87,26.00,41.24,14.46,47496.72,38362.12,2.805,0.05457,1.852,82.30,7.285,48.32
4,2020-04-08,40.34,52.36,63.1,70.57,62.03,25.09,32.84,26.16,43.85,14.24,46689.90,37469.17,2.810,0.05493,1.783,85.34,7.260,45.75

In [5]:
df.shape

(1107, 19)

In [6]:
df.columns

Index(['Date', 'Coal_RB_4800_FOB_London_Close_USD',
       'Coal_RB_5500_FOB_London_Close_USD',
       'Coal_RB_5700_FOB_London_Close_USD',
       'Coal_RB_6000_FOB_CurrentWeek_Avg_USD',
       'Coal_India_5500_CFR_London_Close_USD', 'Price_WTI', 'Price_Brent_Oil',
       'Price_Dubai_Brent_Oil', 'Price_ExxonMobil', 'Price_Shenhua',
       'Price_All_Share', 'Price_Mining',
       'Price_LNG_Japan_Korea_Marker_PLATTS', 'Price_ZAR_USD',
       'Price_Natural_Gas', 'Price_ICE', 'Price_Dutch_TTF',
       'Price_Indian_en_exg_rate'],
      dtype='object')

In [36]:
df.dtypes

Date                                    datetime64[ns]
Coal_RB_4800_FOB_London_Close_USD              float64
Coal_RB_5500_FOB_London_Close_USD              float64
Coal_RB_5700_FOB_London_Close_USD              float64
Coal_RB_6000_FOB_CurrentWeek_Avg_USD           float64
Coal_India_5500_CFR_London_Close_USD           float64
Price_WTI                                      float64
Price_Brent_Oil                                float64
Price_Dubai_Brent_Oil                          float64
Price_ExxonMobil                               float64
Price_Shenhua                                  float64
Price_All_Share                                float64
Price_Mining                                   float64
Price_LNG_Japan_Korea_Marker_PLATTS            float64
Price_ZAR_USD                                  float64
Price_Natural_Gas                              float64
Price_ICE                                      float64
Price_Dutch_TTF                                float64
Price_Indian_en_exg_rate                       float64
dtype: object

In [8]:
#before data processing
df.describe()

,Date,Coal_RB_4800_FOB_London_Close_USD,Coal_RB_5500_FOB_London_Close_USD,Coal_RB_5700_FOB_London_Close_USD,Coal_RB_6000_FOB_CurrentWeek_Avg_USD,Coal_India_5500_CFR_London_Close_USD,Price_WTI,Price_Brent_Oil,Price_Dubai_Brent_Oil,Price_ExxonMobil,Price_Shenhua,Price_All_Share,Price_Mining,Price_LNG_Japan_Korea_Marker_PLATTS,Price_ZAR_USD,Price_Natural_Gas,Price_ICE,Price_Dutch_TTF,Price_Indian_en_exg_rate
count,1107,1068.000000,1068.000000,1068.000000,1084.000000,1068.000000,1099.000000,1096.000000,1067.000000,1067.000000,1042.000000,1058.000000,1058.000000,1066.000000,1107.000000,1099.000000,1067.000000,1076.000000,1047.000000
mean,2022-05-16 14:22:26.341463296,87.953184,113.353155,134.971807,144.351494,123.759710,72.345469,76.283020,74.752493,80.871012,21.274702,68736.904811,52972.178374,17.622529,0.059943,3.697999,112.756111,57.384856,141.616027
min,2020-04-02 00:00:00,26.750000,34.560000,44.690000,44.530000,41.810000,-37.630000,19.330000,19.070000,31.570000,12.060000,44598.700000,35258.300000,1.995000,0.050470,1.482000,80.990000,3.510000,45.020000
25%,2021-04-24 12:00:00,50.370000,67.880000,83.400000,92.420000,81.990000,64.225000,67.457500,65.480000,56.035000,15.275000,65639.547500,47161.832500,8.851250,0.054290,2.458500,101.900000,22.406250,119.065000
50%,2022-05-17 00:00:00,76.190000,95.800000,108.910000,115.270000,111.200000,75.670000,79.960000,78.790000,86.410000,22.325000,70089.085000,53270.245000,12.902500,0.058720,2.863000,111.960000,35.838500,140.900000
75%,2023-06-07 12:00:00,104.180000,129.260000,155.600000,172.550000,150.040000,83.180000,87.450000,87.275000,106.480000,24.937500,74775.762500,57707.622500,25.993750,0.065640,4.710500,122.620000,83.962500,162.350000
max,2024-06-28 00:00:00,301.090000,360.240000,412.350000,428.220000,312.890000,123.700000,127.980000,122.530000,122.200000,40.300000,80791.360000,75185.760000,69.955000,0.074350,9.647000,139.430000,339.195000,295.250000
std,NaN,47.303473,63.105405,77.472391,83.500186,56.502138,20.605415,20.723186,20.505811,27.771904,6.136281,7928.639789,7037.617925,12.716663,0.006068,1.921176,13.729638,53.328953,54.147294

In [9]:
df.isna().sum()

Date                                     0
Coal_RB_4800_FOB_London_Close_USD       39
Coal_RB_5500_FOB_London_Close_USD       39
Coal_RB_5700_FOB_London_Close_USD       39
Coal_RB_6000_FOB_CurrentWeek_Avg_USD    23
Coal_India_5500_CFR_London_Close_USD    39
Price_WTI                                8
Price_Brent_Oil                         11
Price_Dubai_Brent_Oil                   40
Price_ExxonMobil                        40
Price_Shenhua                           65
Price_All_Share                         49
Price_Mining                            49
Price_LNG_Japan_Korea_Marker_PLATTS     41
Price_ZAR_USD                            0
Price_Natural_Gas                        8
Price_ICE                               40
Price_Dutch_TTF                         31
Price_Indian_en_exg_rate                60
dtype: int64

In [10]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1102    False
1103    False
1104    False
1105    False
1106    False
Length: 1107, dtype: bool

In [14]:
cols = ['Coal_RB_4800_FOB_London_Close_USD',
        'Coal_RB_5500_FOB_London_Close_USD',
       'Coal_RB_5700_FOB_London_Close_USD',
       'Coal_RB_6000_FOB_CurrentWeek_Avg_USD',
       'Coal_India_5500_CFR_London_Close_USD']

df[cols] = df[cols].fillna(method='ffill')

C:\Users\HP\AppData\Local\Temp\ipykernel_21304\1390332658.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[cols] = df[cols].fillna(method='ffill')

In [21]:
price_cols = [
    'Price_WTI',
    'Price_Brent_Oil',
    'Price_Dubai_Brent_Oil',
    'Price_Natural_Gas',
    'Price_Dutch_TTF',
    'Price_ICE',
    'Price_Mining',
    'Price_All_Share',
    'Price_ExxonMobil',
    'Price_Shenhua',
    'Price_ZAR_USD',
    'Price_Indian_en_exg_rate',
    'Price_LNG_Japan_Korea_Marker_PLATTS'
]

df[price_cols] = df[price_cols].interpolate(method='linear')

In [29]:
df.loc[0, 'Price_Indian_en_exg_rate'] = df['Price_Indian_en_exg_rate'].bfill().iloc[0]

In [35]:
df.isna().sum()

Date                                    0
Coal_RB_4800_FOB_London_Close_USD       0
Coal_RB_5500_FOB_London_Close_USD       0
Coal_RB_5700_FOB_London_Close_USD       0
Coal_RB_6000_FOB_CurrentWeek_Avg_USD    0
Coal_India_5500_CFR_London_Close_USD    0
Price_WTI                               0
Price_Brent_Oil                         0
Price_Dubai_Brent_Oil                   0
Price_ExxonMobil                        0
Price_Shenhua                           0
Price_All_Share                         0
Price_Mining                            0
Price_LNG_Japan_Korea_Marker_PLATTS     0
Price_ZAR_USD                           0
Price_Natural_Gas                       0
Price_ICE                               0
Price_Dutch_TTF                         0
Price_Indian_en_exg_rate                0
dtype: int64

In [32]:
df.reset_index

<bound method DataFrame.reset_index of            Date  Coal_RB_4800_FOB_London_Close_USD  \
0    2020-04-02                              41.00
1    2020-04-03                              40.34
2    2020-04-06                              40.34
3    2020-04-07                              40.34
4    2020-04-08                              40.34
...         ...                                ...
1102 2024-06-24                              73.30
1103 2024-06-25                              73.30
1104 2024-06-26                              73.30
1105 2024-06-27                              73.30
1106 2024-06-28                              71.38

      Coal_RB_5500_FOB_London_Close_USD  Coal_RB_5700_FOB_London_Close_USD  \
0                                 53.22                              64.70
1                                 52.36                              63.10
2                                 52.36                              63.10
3                                 52.36                              63.10
4                                 52.36                              63.10
...                                 ...                                ...
1102                              94.56                             107.31
1103                              94.56                             107.31
1104                              94.56                             107.31
1105                              94.56                             107.31
1106                              92.08                             103.68

      Coal_RB_6000_FOB_CurrentWeek_Avg_USD  \
0                                    97.56
1                                    70.57
2                                    70.57
3                                    70.57
4                                    70.57
...                                    ...
1102                                106.22
1103                                106.22
1104                                106.22
1105                                106.22
1106                                106.22

      Coal_India_5500_CFR_London_Close_USD  Price_WTI  Price_Brent_Oil  \
0                                    60.50      25.32            29.94
1                                    62.03      28.34            34.11
2                                    62.03      26.08            33.05
3                                    62.03      23.63            31.87
4                                    62.03      25.09            32.84
...                                    ...        ...              ...
1102                                111.20      81.63            86.01
1103                                111.20      80.83            85.01
1104                                111.20      80.90            85.25
1105                                111.20      81.74            86.39
1106                                109.15      81.54            86.41

      Price_Dubai_Brent_Oil  Price_ExxonMobil  Price_Shenhua  Price_All_Share  \
0                     26.16             40.40          14.58         45060.69
1                     29.39             39.21          14.14         44598.70
2                     27.45             40.47          14.26         46240.35
3                     26.00             41.24          14.46         47496.72
4                     26.16             43.85          14.24         46689.90
...                     ...               ...            ...              ...
1102                  82.60            114.05          39.55         80263.14
1103                  82.42            114.37          39.50         79577.57
1104                  82.47            114.41          39.70         79252.39
1105                  82.49            114.90          35.15         78969.33
1106                  82.55            115.12          35.95         79707.11

      Price_Mining  Price_LNG_Japan_Korea_Marker_PLATTS  Price_ZAR_USD  \
0         35562.37                                2.860        0.05411
1         35258.30                                2.845        0.05245
2         37032.31                                2.850        0.05351
3         38362.12                                2.805        0.05457
4         37469.17                                2.810        0.05493
...            ...                                  ...            ...
1102      51492.93                               12.610        0.05517
1103      51015.62                               12.735        0.05482
1104      50943.54                               12.620        0.05497
1105      52018.94                               12.660        0.05411
1106      51308.87                               12.635        0.05495

      Price_Natural_Gas  Price_ICE  Price_Dutch_TTF  Price_Indian_en_exg_rate
0                 1.552      81.14            6.935                     45.02
1                 1.621      80.99            6.920                     45.02
2                 1.731      84.43            7.285                     46.67
3                 1.852      82.30            7.285                     48.32
4                 1.783      85.34            7.260                     45.75
...                 ...        ...              ...                       ...
1102              2.811     138.72           34.080                    182.69
1103              2.756     137.33           34.855                    179.47
1104              2.628     137.39           33.825                    178.68
1105              2.685     137.47           34.565                    179.83
1106              2.601     136.89           34.480                    180.54

[1107 rows x 19 columns]>

In [37]:
df['Date'] = pd.to_datetime(df['Date'])

In [38]:
df.to_excel('cleaned_data.xlsx', index=False)

In [41]:
# Expoloratory Data Analysis (EDA)

In [46]:
df.mean(numeric_only=True)

Coal_RB_4800_FOB_London_Close_USD          88.039711
Coal_RB_5500_FOB_London_Close_USD         113.445727
Coal_RB_5700_FOB_London_Close_USD         135.082945
Coal_RB_6000_FOB_CurrentWeek_Avg_USD      144.396902
Coal_India_5500_CFR_London_Close_USD      123.827380
Price_WTI                                  72.296495
Price_Brent_Oil                            76.254277
Price_Dubai_Brent_Oil                      74.738695
Price_ExxonMobil                           80.935601
Price_Shenhua                              21.306021
Price_All_Share                         68754.383189
Price_Mining                            53023.681477
Price_LNG_Japan_Korea_Marker_PLATTS        17.615676
Price_ZAR_USD                               0.059943
Price_Natural_Gas                           3.693624
Price_ICE                                 112.787556
Price_Dutch_TTF                            57.302042
Price_Indian_en_exg_rate                  141.561350
dtype: float64

In [47]:
df.median(numeric_only=True)

Coal_RB_4800_FOB_London_Close_USD          76.19000
Coal_RB_5500_FOB_London_Close_USD          95.80000
Coal_RB_5700_FOB_London_Close_USD         108.91000
Coal_RB_6000_FOB_CurrentWeek_Avg_USD      115.27000
Coal_India_5500_CFR_London_Close_USD      111.20000
Price_WTI                                  75.66000
Price_Brent_Oil                            79.98000
Price_Dubai_Brent_Oil                      78.69000
Price_ExxonMobil                           86.81000
Price_Shenhua                              22.40000
Price_All_Share                         70264.11000
Price_Mining                            53284.84000
Price_LNG_Japan_Korea_Marker_PLATTS        12.88500
Price_ZAR_USD                               0.05872
Price_Natural_Gas                           2.85500
Price_ICE                                 112.00000
Price_Dutch_TTF                            35.81000
Price_Indian_en_exg_rate                  140.70000
dtype: float64

In [49]:
df.mode(numeric_only=True)

,Coal_RB_4800_FOB_London_Close_USD,Coal_RB_5500_FOB_London_Close_USD,Coal_RB_5700_FOB_London_Close_USD,Coal_RB_6000_FOB_CurrentWeek_Avg_USD,Coal_India_5500_CFR_London_Close_USD,Price_WTI,Price_Brent_Oil,Price_Dubai_Brent_Oil,Price_ExxonMobil,Price_Shenhua,Price_All_Share,Price_Mining,Price_LNG_Japan_Korea_Marker_PLATTS,Price_ZAR_USD,Price_Natural_Gas,Price_ICE,Price_Dutch_TTF,Price_Indian_en_exg_rate
0,95.97,47.56,50.12,115.27,249.34,78.26,72.22,43.78,64.31,22.50,44598.70,35258.30,2.0,0.05273,2.492,90.40,7.280,133.0
1,NaN,NaN,51.58,NaN,NaN,NaN,77.59,43.96,104.29,24.75,45060.69,35562.37,2.2,0.05429,2.520,93.24,13.900,145.1
2,NaN,NaN,81.81,NaN,NaN,NaN,82.96,83.56,105.88,NaN,46240.35,37032.31,NaN,0.05506,2.608,93.77,19.170,NaN
3,NaN,NaN,82.07,NaN,NaN,NaN,84.03,NaN,109.11,NaN,46689.90,37469.17,NaN,0.06308,2.731,96.68,27.340,NaN
4,NaN,NaN,101.66,NaN,NaN,NaN,85.34,NaN,NaN,NaN,47496.72,38362.12,NaN,0.06532,NaN,103.93,33.795,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80263.14,74495.79,NaN,NaN,NaN,NaN,NaN,NaN
1103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80324.86,74666.11,NaN,NaN,NaN,NaN,NaN,NaN
1104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80508.97,74773.64,NaN,NaN,NaN,NaN,NaN,NaN
1105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80713.72,75128.44,NaN,NaN,NaN,NaN,NaN,NaN
1106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80791.36,75185.76,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df.var(numeric_only=True)

Coal_RB_4800_FOB_London_Close_USD       2.251036e+03
Coal_RB_5500_FOB_London_Close_USD       4.000715e+03
Coal_RB_5700_FOB_London_Close_USD       6.022772e+03
Coal_RB_6000_FOB_CurrentWeek_Avg_USD    6.969031e+03
Coal_India_5500_CFR_London_Close_USD    3.198582e+03
Price_WTI                               4.262519e+02
Price_Brent_Oil                         4.297495e+02
Price_Dubai_Brent_Oil                   4.195151e+02
Price_ExxonMobil                        7.705532e+02
Price_Shenhua                           3.769252e+01
Price_All_Share                         6.339047e+07
Price_Mining                            4.940211e+07
Price_LNG_Japan_Korea_Marker_PLATTS     1.608962e+02
Price_ZAR_USD                           3.681609e-05
Price_Natural_Gas                       3.690233e+00
Price_ICE                               1.883352e+02
Price_Dutch_TTF                         2.836907e+03
Price_Indian_en_exg_rate                2.928001e+03
dtype: float64

In [51]:
df.std(numeric_only=True)

Coal_RB_4800_FOB_London_Close_USD         47.445087
Coal_RB_5500_FOB_London_Close_USD         63.251209
Coal_RB_5700_FOB_London_Close_USD         77.606518
Coal_RB_6000_FOB_CurrentWeek_Avg_USD      83.480724
Coal_India_5500_CFR_London_Close_USD      56.556012
Price_WTI                                 20.645868
Price_Brent_Oil                           20.730400
Price_Dubai_Brent_Oil                     20.482069
Price_ExxonMobil                          27.758840
Price_Shenhua                              6.139423
Price_All_Share                         7961.813549
Price_Mining                            7028.663154
Price_LNG_Japan_Korea_Marker_PLATTS       12.684487
Price_ZAR_USD                              0.006068
Price_Natural_Gas                          1.920998
Price_ICE                                 13.723529
Price_Dutch_TTF                           53.262625
Price_Indian_en_exg_rate                  54.111005
dtype: float64

In [52]:
df.max(numeric_only=True) - df.min(numeric_only=True)

Coal_RB_4800_FOB_London_Close_USD         274.34000
Coal_RB_5500_FOB_London_Close_USD         325.68000
Coal_RB_5700_FOB_London_Close_USD         367.66000
Coal_RB_6000_FOB_CurrentWeek_Avg_USD      383.69000
Coal_India_5500_CFR_London_Close_USD      271.08000
Price_WTI                                 161.33000
Price_Brent_Oil                           108.65000
Price_Dubai_Brent_Oil                     103.46000
Price_ExxonMobil                           90.63000
Price_Shenhua                              28.24000
Price_All_Share                         36192.66000
Price_Mining                            39927.46000
Price_LNG_Japan_Korea_Marker_PLATTS        67.96000
Price_ZAR_USD                               0.02388
Price_Natural_Gas                           8.16500
Price_ICE                                  58.44000
Price_Dutch_TTF                           335.68500
Price_Indian_en_exg_rate                  250.23000
dtype: float64

In [53]:
df.skew(numeric_only=True)

Coal_RB_4800_FOB_London_Close_USD       1.308683
Coal_RB_5500_FOB_London_Close_USD       1.258624
Coal_RB_5700_FOB_London_Close_USD       1.275821
Coal_RB_6000_FOB_CurrentWeek_Avg_USD    1.272242
Coal_India_5500_CFR_London_Close_USD    0.861806
Price_WTI                              -0.533359
Price_Brent_Oil                        -0.428092
Price_Dubai_Brent_Oil                  -0.559972
Price_ExxonMobil                       -0.211970
Price_Shenhua                           0.552163
Price_All_Share                        -0.836074
Price_Mining                            0.270996
Price_LNG_Japan_Korea_Marker_PLATTS     1.085616
Price_ZAR_USD                           0.347963
Price_Natural_Gas                       1.262572
Price_ICE                               0.218916
Price_Dutch_TTF                         1.716831
Price_Indian_en_exg_rate                0.366363
dtype: float64

In [54]:
df.kurt(numeric_only=True)

Coal_RB_4800_FOB_London_Close_USD       2.046083
Coal_RB_5500_FOB_London_Close_USD       1.090233
Coal_RB_5700_FOB_London_Close_USD       0.785208
Coal_RB_6000_FOB_CurrentWeek_Avg_USD    0.718840
Coal_India_5500_CFR_London_Close_USD    0.159394
Price_WTI                               0.787987
Price_Brent_Oil                        -0.028752
Price_Dubai_Brent_Oil                  -0.031079
Price_ExxonMobil                       -1.488041
Price_Shenhua                          -0.007373
Price_All_Share                        -0.107347
Price_Mining                           -0.376979
Price_LNG_Japan_Korea_Marker_PLATTS     0.792650
Price_ZAR_USD                          -1.217152
Price_Natural_Gas                       0.663970
Price_ICE                              -0.874255
Price_Dutch_TTF                         3.132558
Price_Indian_en_exg_rate               -0.086253
dtype: float64

In [55]:
summary = pd.DataFrame({
    'Mean': df.mean(numeric_only=True),
    'Median': df.median(numeric_only=True),
    'Std Dev': df.std(numeric_only=True),
    'Variance': df.var(numeric_only=True),
    'Skewness': df.skew(numeric_only=True),
    'Kurtosis': df.kurt(numeric_only=True)
})

print(summary)

                                              Mean       Median      Std Dev  \
Coal_RB_4800_FOB_London_Close_USD        88.039711     76.19000    47.445087
Coal_RB_5500_FOB_London_Close_USD       113.445727     95.80000    63.251209
Coal_RB_5700_FOB_London_Close_USD       135.082945    108.91000    77.606518
Coal_RB_6000_FOB_CurrentWeek_Avg_USD    144.396902    115.27000    83.480724
Coal_India_5500_CFR_London_Close_USD    123.827380    111.20000    56.556012
Price_WTI                                72.296495     75.66000    20.645868
Price_Brent_Oil                          76.254277     79.98000    20.730400
Price_Dubai_Brent_Oil                    74.738695     78.69000    20.482069
Price_ExxonMobil                         80.935601     86.81000    27.758840
Price_Shenhua                            21.306021     22.40000     6.139423
Price_All_Share                       68754.383189  70264.11000  7961.813549
Price_Mining                          53023.681477  53284.84000  7028.663154
Price_LNG_Japan_Korea_Marker_PLATTS      17.615676     12.88500    12.684487
Price_ZAR_USD                             0.059943      0.05872     0.006068
Price_Natural_Gas                         3.693624      2.85500     1.920998
Price_ICE                               112.787556    112.00000    13.723529
Price_Dutch_TTF                          57.302042     35.81000    53.262625
Price_Indian_en_exg_rate                141.561350    140.70000    54.111005

                                          Variance  Skewness  Kurtosis
Coal_RB_4800_FOB_London_Close_USD     2.251036e+03  1.308683  2.046083
Coal_RB_5500_FOB_London_Close_USD     4.000715e+03  1.258624  1.090233
Coal_RB_5700_FOB_London_Close_USD     6.022772e+03  1.275821  0.785208
Coal_RB_6000_FOB_CurrentWeek_Avg_USD  6.969031e+03  1.272242  0.718840
Coal_India_5500_CFR_London_Close_USD  3.198582e+03  0.861806  0.159394
Price_WTI                             4.262519e+02 -0.533359  0.787987
Price_Brent_Oil                       4.297495e+02 -0.428092 -0.028752
Price_Dubai_Brent_Oil                 4.195151e+02 -0.559972 -0.031079
Price_ExxonMobil                      7.705532e+02 -0.211970 -1.488041
Price_Shenhua                         3.769252e+01  0.552163 -0.007373
Price_All_Share                       6.339047e+07 -0.836074 -0.107347
Price_Mining                          4.940211e+07  0.270996 -0.376979
Price_LNG_Japan_Korea_Marker_PLATTS   1.608962e+02  1.085616  0.792650
Price_ZAR_USD                         3.681609e-05  0.347963 -1.217152
Price_Natural_Gas                     3.690233e+00  1.262572  0.663970
Price_ICE                             1.883352e+02  0.218916 -0.874255
Price_Dutch_TTF                       2.836907e+03  1.716831  3.132558
Price_Indian_en_exg_rate              2.928001e+03  0.366363 -0.086253

In [57]:
summary.to_excel('Statistical_data.xlsx')